### ISSUE TITLE
Hard to read font in Whisker menu

### ISSUE THREAD

**Issue by Photon89** [oberon2007/vertex-maia-themes#7]
After the update to 2.x the Whisker menu shows the same problematic behaviour as other applets did in the past. Looks like there is a fix though: https://forum.manjaro.org/t/whisker-menu-not-conforming-to-the-system-theme/44903/17

**Comment by Photon89** [comment]
Figured out what you should add to actually fix the panel button:

```
#whiskermenu-button { 
	color: #ffffff;
	padding-top: 2px;
}
```

**Comment by oberon-manjaro** [comment]
Great, I'll add that. Thank you @Photon89 
I suppose this goes in [here](https://github.com/oberon2007/vertex-theme/blob/master/common/gtk-3.0/3.20/gtk.css#L4332), right?

**Comment by Photon89** [comment]
Yep, thanks! :smiley:

**Comment by oberon-manjaro** [comment]
So if this works, we should be able to find a similar solution for the clock applet and others - just would need to find out the right property names ... ...

**Comment by Photon89** [comment]
I was also thinking about it, will have a look in the evening.

**Comment by oberon-manjaro** [comment]
should be one of the button properties in **.xfce4-panel.panel**
Or just adding for the panel in general.
I will also play with it a little ... ;)

**Comment by Photon89** [comment]
Would be cool, if the problem could be fixed once and for all with a panel-wide option!

**Comment by Photon89** [comment]
Btw., I've two offtopic questions: Is this repository obsolete (since the actual development happens in https://github.com/oberon2007/vertex-theme)? And has the default Manjaro Xfce theme been changed to some different theme (since nobody complained about the Whisker menu button font issue on the forums)?

**Comment by oberon-manjaro** [comment]
In this case it's a topic concerning vertex-themes altogether, but It doesn't really matter. ;)
Looks like I'm getting there! I have now moved text settings to panel buttons more general. Seems like that we can drop the specific whiskermenu and most likely also power-manager settings.
What doesn't look perfect, yet is that text appears thinner - I guess it has actually to do with outline or shadow, not really the font.
Currently I have the whole section looking like this:
```
.xfce4-panel.panel {
  background-color: #3C3E40; }
  .xfce4-panel.panel button.flat, .xfce4-panel.panel button.sidebar-button {
    color: #f3f3f5;
    padding-top: 2px;
    background-color: rgba(60, 62, 64, 0);
    border-radius: 0;
    text-shadow: 0 -1px rgba(0, 0, 0, 0.7);
    -gtk-icon-shadow: 0 -1px rgba(0, 0, 0, 0.7); }
    .xfce4-panel.panel button.flat:hover, .xfce4-panel.panel button.sidebar-button:hover {
      outline-color: rgba(243, 243, 245, 0.3);
      background-image: linear-gradient(to bottom, #5e6064, #393A3B);
      text-shadow: 0 -1px rgba(0, 0, 0, 0.7);
      -gtk-icon-shadow: 0 -1px rgba(0, 0, 0, 0.7);
      border-image: -gtk-scaled(url("borders/button-normal-border-dark.png"), url("borders/button-normal-border-dark@2.png")) 2 2 3 2/2px 2px 3px 2px stretch;
      border-radius: 2px;
      border-width: 1px 1px 2px 1px;
      border-style: solid;
      border-color: transparent;
      border-radius: 0; }
    .xfce4-panel.panel button.flat:active, .xfce4-panel.panel button.sidebar-button:active, .xfce4-panel.panel button.flat:checked, .xfce4-panel.panel button.sidebar-button:checked {
      outline-color: rgba(255, 255, 255, 0.3);
      background-image: linear-gradient(to bottom, #242525, #37383A);
      text-shadow: 0 -1px rgba(0, 0, 0, 0.4);
      -gtk-icon-shadow: 0 -1px rgba(0, 0, 0, 0.4);
      box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.2);
      border-image: -gtk-scaled(url("borders/button-active-border-dark.png"), url("borders/button-active-border-dark@2.png")) 2 2 3 2/2px 2px 3px 2px stretch;
      border-radius: 2px;
      border-width: 1px 1px 2px 1px;
      border-style: solid;
      border-color: transparent;
      border-radius: 0; }
```
with this effect on the whiskermenu:

![screenshot_2018-04-24_13-17-46](https://user-images.githubusercontent.com/11800714/39183944-031bc096-47c2-11e8-99db-0c2ecb47b5e3.png)

and also the clock is now readable:

![screenshot_2018-04-24_13-18-02](https://user-images.githubusercontent.com/11800714/39183963-11b5d920-47c2-11e8-868d-6faa20363da8.png)

However, what would really be great to achieve is how it looks with vertex-dark:

![screenshot_2018-04-24_13-19-51](https://user-images.githubusercontent.com/11800714/39184013-3b492d3c-47c2-11e8-8891-515cba40a12e.png)

**Comment by oberon-manjaro** [comment]
Oh well :laughing: actually, it wasn't so hard...
You add
```
font-weight: bold;
```
and you get, erm,  bold text :rofl: 
![screenshot_2018-04-24_13-31-14](https://user-images.githubusercontent.com/11800714/39184489-d3ea1ea6-47c3-11e8-8821-f3b6edd27f66.png)

**Comment by oberon-manjaro** [comment]
Could you remind me again, in which situation the **power-manager-plugin** displays text in the panel? I can only get it to display an icon.
I am trying to figure out if the global panel setting is now sufficient and the power-manager property can be removed... ?

**Comment by oberon-manjaro** [comment]
The other part of your question: It looks like the 18.0 release will be using **adapta-maia** themes.

**Comment by Photon89** [comment]
You can add it from the applet list, additionally to the power-manager's tray icon.

**Comment by Photon89** [comment]
Concerning bold fonts: Actually, I'd rather vote for using regular fonts to match gtk2 plugins which also use regular fonts.

**Comment by oberon-manjaro** [comment]
Right. I can remove the extra `bold`specification, but the behaviour is still a bit mysterious. You will see ... ;)
Additionally I now found a way to recreate Rabideau's old version of our two colored whiskermenu. I will include this in the regular **vertex-maia** version. So it will look the way we were used to, again...

![screenshot_2018-04-24_16-36-46](https://user-images.githubusercontent.com/11800714/39194775-b50881c4-47de-11e8-94a7-94edee1acdc5.png)

**Comment by oberon-manjaro** [comment]
Ok. power-manager-applet now also has white text with the global panel css. So I assume this should finally take care of any other applets, aswell.

**Comment by Photon89** [comment]
Very cool, I'm excited to test it once it hits stable! :smiley:

**Comment by Photon89** [comment]
Concerning bold fonts in the Dark version of Vertex Maia: I think, it might be a fix which you applied to the regular version but not to the other ones, probably the fix of this issue: https://github.com/oberon2007/vertex-maia-themes/issues/4 I think, on the short run it would make sense to make fonts regular for all versions as long as the transition to GTK3 is not complete, to preserve consistency. Once all plugins have shifted to GTK3 it will be a matter of taste if bold or regular (I am currently more used to regular, but looks like the modern world shifts to bold lately).

**Comment by oberon-manjaro** [comment]
You can install the new version from testing branch:
```
sudo pacman -U https://www.uex.dk/public/manjaro/pool/overlay/vertex-maia-themes-20180424-3-any.pkg.tar.xz
```
:grin:

**Comment by Photon89** [comment]
Cool, thanks! Did you also include the padding option? With the testing package the padding is 1px off:

![auswahl_003](https://user-images.githubusercontent.com/1191480/39205661-9a1d36ee-47fb-11e8-96df-9357d9bfedfa.png)

edit: The padding thing might actually be a bug in Whisker menu itself, all other plugins align nicely, including GTK3 ones, just Whisker is one pixel off...

**Comment by oberon-manjaro** [comment]
I did:
https://github.com/oberon2007/vertex-theme/blob/master/common/gtk-3.0/3.20/gtk.css#L4302
`padding-top: 2px;`

Maybe we need a bit more... 4px?

**Comment by oberon-manjaro** [comment]
The direction of shadows is also different hm. Sorry, what is it I'm seeing there? "Orte" ?

**Comment by Photon89** [comment]
It's the "Places" plugin (available through the AUR). :smiley: But the same padding difference is visible between Whisker and all other plugins.
I think, the padding should be applied to whiskermenu-button only, otherwise all GTK3 plugins are shifted which we don't want. 2px worked for me when I was testing around.
Didn't notice the shadow difference, I will have a look how other plugins behave!

**Comment by Photon89** [comment]
Concerning the shadow, looks like GTK3 applets consistently drop a shadow upwards and GTK2 applets again consistently drop a shadow downwards... Don't know if it is possible to do something about it. But it is hardly visible if you don't zoom in.

**Comment by oberon-manjaro** [comment]
I see. I was my mistake to apply the padding for everything instead of just whiskermenu-button :wink: 
Do we need that in the dark theme aswell?

**Comment by oberon-manjaro** [comment]
Hm. Somehow I can't seem to reproduce this on my xfce4-gtk3 install. Everything seems to be aligned here even when I remove the padding entry altogether:
![screenshot_2018-04-24_21-24-04](https://user-images.githubusercontent.com/11800714/39209501-36df68e4-4806-11e8-8546-93bca19598c9.png)

So I guess this might be an issue only still with xfce4-gtk2
I'll leave it in the whiskermenu-button property for now in any case ...

**Comment by Photon89** [comment]
I think, the padding is necessary in all variants. Since the bold font issue is not yet fixed in the Dark and Light variants, the padding issue is not that striking probably. How does xfce4-gtk3 actually handle plugins which are still written using GTK2 (concerning theming in particular)?
